// Builds the site icons from the brand source, never by hand (design/brand.md).
//
//   node scripts/brand/build-icons.mjs
//
// The symbol is the SECOND "A" of the KUASAR wordmark, the tall rocket-shaped A between S
// and R, taken as its exact <path> from apps/web/public/brand/kuasar-wordmark.svg (the
// glyph under the plain `<!-- A -->` comment). It is drawn in --color-ink on a
// --color-space-950 square, both read from apps/web/app/globals.css, so it stays visible in
// light and dark browser UI. Outputs, in Next.js App Router metadata-file conventions:
//   apps/web/app/icon.svg        vector favicon (<link rel="icon" type="image/svg+xml">)
//   apps/web/app/favicon.ico     16, 32 and 48 px PNG-in-ICO fallback (/favicon.ico)
//   apps/web/app/apple-icon.png  180 x 180 Apple touch icon
// Re-run after any change to the wordmark or those two tokens, and commit the outputs.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '../..');
const web = resolve(root, 'apps/web');
const sharp = createRequire(resolve(web, 'package.json'))('sharp');

// --- The glyph: the exact second-A path from the brand SVG.
const wordmark = readFileSync(resolve(web, 'public/brand/kuasar-wordmark.svg'), 'utf8');
const match = /<!-- A -->\s*(<path\b[^>]*\/>)/.exec(wordmark);
if (!match) throw new Error('Second "A" (<!-- A --> path) not found in kuasar-wordmark.svg');
const glyph = match[1];
const d = /\bd="([^"]+)"/.exec(glyph)?.[1];
if (!d || /[a-z]/.test(d.replace(/[eE]/g, ''))) throw new Error('Expected an absolute-command path for the second "A"');
// Bounds from the absolute coordinates (M/L pairs, H x, V y), plus the 1-unit stroke.
const xs = [], ys = [];
for (const [, cmd, args] of d.matchAll(/([MLHVZ])([^MLHVZ]*)/g)) {
  const n = args.trim() ? args.trim().split(/[\s,]+/).map(Number) : [];
  if (cmd === 'H') xs.push(...n); else if (cmd === 'V') ys.push(...n);
  else for (let i = 0; i < n.length; i += 2) { xs.push(n[i]); ys.push(n[i + 1]); }
}
const stroke = 0.5;
const box = { x0: Math.min(...xs) - stroke, x1: Math.max(...xs) + stroke, y0: Math.min(...ys) - stroke, y1: Math.max(...ys) + stroke };

// --- Colours: the brand tokens, converted from OKLCH to sRGB hex (CSS Color 4 math).
const css = readFileSync(resolve(web, 'app/globals.css'), 'utf8');
function token(name) {
  const m = new RegExp(`--color-${name}:\\s*oklch\\(([\\d.]+)\\s+([\\d.]+)\\s+([\\d.]+)\\)`).exec(css);
  if (!m) throw new Error(`--color-${name} (oklch) not found in globals.css`);
  const [L, C, h] = m.slice(1).map(Number);
  const a = C * Math.cos((h * Math.PI) / 180), b = C * Math.sin((h * Math.PI) / 180);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const mm = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  const lin = [4.0767416621 * l - 3.3077115913 * mm + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * mm - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * mm + 1.707614701 * s];
  return `#${lin.map((x) => {
    const c = Math.min(1, Math.max(0, x));
    return Math.round((c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055) * 255).toString(16).padStart(2, '0');
  }).join('')}`;
}
const background = token('space-950');
const ink = token('ink');

// --- Layout: a square viewBox centred on the glyph; the glyph is 72% of the height, so
// ~14% padding top and bottom, which keeps the rocket legible at 16 px.
const height = box.y1 - box.y0;
const side = height / 0.72;
const cx = (box.x0 + box.x1) / 2, cy = (box.y0 + box.y1) / 2;
const vb = [cx - side / 2, cy - side / 2, side, side].map((n) => +n.toFixed(2));
const symbol = glyph.replace(/currentColor/g, ink);
const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb.join(' ')}">
  <!-- Generated by scripts/brand/build-icons.mjs from public/brand/kuasar-wordmark.svg (second "A"). Do not edit. -->
  <rect x="${vb[0]}" y="${vb[1]}" width="${side.toFixed(2)}" height="${side.toFixed(2)}" fill="${background}"/>
  ${symbol}
</svg>
`;

const png = (size) => sharp(Buffer.from(iconSvg), { density: Math.max(72, (72 * size) / side * 4) })
  .resize(size, size).png({ compressionLevel: 9 }).toBuffer();

// --- favicon.ico: an ICO container of PNG images (supported by every current browser).
async function ico(sizes) {
  const images = await Promise.all(sizes.map(png));
  const header = Buffer.alloc(6 + 16 * images.length);
  header.writeUInt16LE(0, 0); header.writeUInt16LE(1, 2); header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach((img, i) => {
    const e = 6 + 16 * i, s = sizes[i];
    header.writeUInt8(s >= 256 ? 0 : s, e); header.writeUInt8(s >= 256 ? 0 : s, e + 1);
    header.writeUInt8(0, e + 2); header.writeUInt8(0, e + 3);
    header.writeUInt16LE(1, e + 4); header.writeUInt16LE(32, e + 6);
    header.writeUInt32LE(img.length, e + 8); header.writeUInt32LE(offset, e + 12);
    offset += img.length;
  });
  return Buffer.concat([header, ...images]);
}

writeFileSync(resolve(web, 'app/icon.svg'), iconSvg);
writeFileSync(resolve(web, 'app/favicon.ico'), await ico([16, 32, 48]));
writeFileSync(resolve(web, 'app/apple-icon.png'), await png(180));
console.log(`icons built: glyph box ${JSON.stringify(box)}, viewBox ${vb.join(' ')}, background ${background}, symbol ${ink}`);
